framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

when@dev:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'
            envelope:
                recipients: ['fabrice@insideweb.be', 'jonahtan@verhulst.be']