monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404, 405]
            grouped:
                type: group
                members: [ nested, discord ]
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 30
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            discord:
                type: service
                id: Proglab\DiscordHandler
                channels: ["!deprecation"]
when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: grouped
                excluded_http_codes: [404]
            grouped:
                type: group
                members: [ nested, discord ]
            nested:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 30
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!deprecation"]
            discord:
                type: service
                id: DiscordHandler\DiscordHandler
                channels: ["!deprecation"]
            deprecation:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.deprecation.log"
                level: debug
                max_files: 10
                channels: [deprecation]
