framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        providers:
            crowdin:
                domains:
                    - 'messages'
                    - 'validators'
                    - 'reset_password'
                dsn: '%env(CROWDIN_DSN)%'
                locales:
                    fr: 'fr'
                    en: 'en'
                    nl: 'nl'
