vich_uploader:
    db_driver: orm

    mappings:
        file:
            uri_prefix: /files/pdfs
            upload_destination: '%kernel.project_dir%/shared/var/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        fileFile:
            uri_prefix: /files/pdfs
            upload_destination: '%kernel.project_dir%/shared/var/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
