version: '3'

services:
  ###> Maildev ###
  maildev_server:
    image: maildev/maildev
    container_name: cont_maildev_server
    #This is optional
    tty: true
    ports:
      - '1080:80'
    #This is optional
    #restart: always
    restart: on-failure
    #The same network of the others services
    networks:
      - maildev
  ###< Maildev ###

networks:
  maildev:
