version: '3'

includes:
    base: ./external/Taskfile.yaml

tasks:
    qa:
        desc: Run qa task from base file
        cmds:
            - task base:qa

    test:
        desc: Run tests
        cmds:
            - task: setup_tests
            - symfony php vendor/bin/phpunit

    setup_tests:
        cmds:
            - rm -rf var/cache/dashboard/*
            - task: fixtures_test

    fixtures_test:
        desc: Launch fixtures for dashboard environment
        cmds:
            - rm -rf var/cache/dashboard/*
            - symfony console d:d:d -f --if-exists --quiet --env=dashboard
            - symfony console d:d:c --quiet --env=dashboard
            - symfony console d:s:u -f --quiet --env=dashboard
            - symfony console d:m:sync-metadata-storage --quiet --env=dashboard
            - symfony console d:m:v --add --all --quiet --env=dashboard
            - symfony console d:f:l --quiet --env=dashboard

    fixtures_dev:
        desc: Launch fixtures for dev environment
        cmds:
            - rm -rf var/cache/dev/*
            - symfony console d:d:d -f --if-exists --quiet
            - symfony console d:d:c --quiet
            - symfony console d:s:u -f --quiet
            - symfony console d:m:sync-metadata-storage --quiet
            - symfony console d:m:v --add --all --quiet
            - symfony console d:f:l --quiet

    maildev:
        desc: Launch Maildev
        cmds:
            - maildev --hide-extensions STARTTLS

    update:
        desc: Update the project
        cmds:
            - git pull
            - task: install

    install:
        desc: Install the project
        cmds:
            - docker pull jakzal/phpqa
            - composer install
            - yarn install --force
            - yarn run build
            - task: fixtures_dev
            - task: qa
            - task: dashboard