name: CI (Php Stan + PHP-CS-FIXER + security-checker)

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Clone git
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: phpstan, composer:v2, php-cs-fixer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Get cache
        id: cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run PHPStan
        run: phpstan analyse src

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --config="./.php-cs-fixer.dist.php" --verbose --dry-run --diff --using-cache=no

      - name: Run security checker
        uses: symfonycorp/security-checker-action@v4
