name: Php Cs Fixer

on: [push, workflow_dispatch]

jobs:
  php-cs-fixer:
    name: Php Cs Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - run: docker pull jakzal/phpqa
      - run: docker run --init --rm -v $GITHUB_WORKSPACE:/project -w /project jakzal/phpqa:php8.1-alpine php-cs-fixer fix --config="./.php-cs-fixer.dist.php" --verbose --dry-run --diff --using-cache=no