name: Php Cs Fixer && security checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: PhpStan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: php-cs-fixer

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --config="./.php-cs-fixer.dist.php" --verbose --dry-run --diff --using-cache=no

      - name: Checkout code
        uses: symfonycorp/security-checker-action@v4
