name: Php Cs Fixer && security checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: PhpStan
    runs-on: ubuntu-latest
    container: jakzal/phpqa:1.83.5-php8.1
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --config="./.php-cs-fixer.dist.php" --verbose --dry-run --diff --using-cache=no

      - name: Checkout code
        uses: symfonycorp/security-checker-action@v4
