name: PHP STAN

on: [push, workflow_dispatch]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 6
          memory_limit: -1