name: Php Cs Fixer

on: [push, workflow_dispatch]

jobs:
  php-cs-fixer:
    name: Php Cs Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - run: docker pull jakzal/phpqa
      - run: docker run --init --rm -v $GITHUB_WORKSPACE:/project -w /project jakzal/phpqa php-cs-fixer fix ./src --verbose --dry-run --diff --using-cache=no