name: Security Checker

on: [push, workflow_dispatch]

jobs:
  security-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Checkout code
        uses: actions/cache@v2
        with:
          path: ~/.symfony/cache
          key: db
      - uses: symfonycorp/security-checker-action@v3